- src/main/java/org/mule/extension/ftp/internal/sftp/connection/SftpClient.java
> MULE-12608: Remove com.google.common from exported packages

- src/test/java/org/mule/extension/ftp/internal/sftp/connection/SftpConnectionProviderTestCase.java
- src/test/java/org/mule/extension/sftp/SftpServer.java
- src/test/java/org/mule/extension/sftp/SftpTestHarness.java
* move connector specific stuff to the corresponding connector
> MULE-12255: Migrate testing namespaces to plugins

- src/main/java/org/mule/extension/ftp/internal/FtpConnector.java
_ Defining the privileged API to enable FTPS extension
> MULE-13011: Add privileged API for plugin artifacts

- src/test/java/org/mule/extension/ftp/CommonFtpConnectorTestCase.java
- src/test/java/org/mule/extension/ftp/FtpListTestCase.java
- src/test/java/org/mule/extension/ftp/FtpReadTestCase.java
- src/test/java/org/mule/extension/ftp/FtpWriteTestCase.java
- src/test/java/org/mule/extension/ftp/FtpWriteTypeTestCase.java
* Change security filter return type to 
* Remove some deprecated usages
* Event interface split
> MULE-13363: Allow access to session properties from privileged API

- src/test/java/org/mule/extension/ftp/FtpNegativeConnectivityTestCase.java
> MULE-12716: Remove registries from API

- src/main/java/org/mule/extension/ftp/internal/connection/FtpConnectionProvider.java
> MULE-13814: Remove org.apache.logging.log4j:log4j-slf4j-impl from

- src/main/java/org/mule/extension/ftp/api/FtpFileMatcher.java
- src/main/java/org/mule/extension/ftp/api/ftp/FtpFileAttributes.java
- src/main/java/org/mule/extension/ftp/internal/source/FtpDirectoryListener.java
- src/test/java/org/mule/extension/ftp/FtpFileAttributesTestCase.java
- src/test/java/org/mule/extension/ftp/FtpFileMatcherTestCase.java
(cherry picked from commit 2929ff7)
> MULE-15301: FtpFileAttributes throw NPE when FTPFile date is null (#86)

- src/main/java/org/mule/extension/ftp/internal/FtpUtils.java
- src/test/java/org/mule/extension/ftp/FtpDirectoryListenerFunctionalTestCase.java
- src/test/java/org/mule/extension/ftp/FtpFileAttributesTestCase.java
Fixing failing tests in Windows due to differences between absolute and relative paths..
> MULE-15914: Fix FTP connector tests in Windows

- src/main/java/org/mule/extension/ftp/internal/source/FtpDirectoryListener.java
- src/test/munit/configurations.xml
- src/test/munit/ftp-directory-listener-post-processing-action-test-case.xml
Syncronized the post processing action and cached the connection in order to avoid conflicts when executing post action step.
> FTPC-67: Fixed "On new or updated file" post action

- src/main/java/org/mule/extension/ftp/internal/source/FtpDirectoryListener.java
- src/test/munit/configurations.xml
- src/test/munit/ftp-directory-listener-post-processing-action-test-case.xml
(cherry picked from commit 915e6a27cca2454841b37380b20a1a6e73d70f6a)
> FTPC-67: Fixed "On new or updated file" post action (#194)

- src/main/java/org/mule/extension/ftp/internal/connection/FtpFileSystem.java
- src/main/java/org/mule/extension/ftp/internal/source/FtpDirectoryListener.java
- src/test/munit/ftp-directory-listener-reconnection-test-case.xml
* FTPC-75: fixed reconnection on directory listener
(cherry picked from commit 349178df8a7ce5bd949ca0e4b29ce5e2adbb11a5)
> FTC-75 support/1.5.x

- src/main/java/org/mule/extension/ftp/internal/source/PostActionGroup.java
- src/test/java/org/mule/extension/ftp/PostActionGroupTestCase.java
update postActionGroup since the parent class in file common got updated
> W-11427407 update postActionGroup since the parent class in file common got updated

- pom.xml
W-11427407 update pom.xml for FTP connector
> W-11427407 update pom.xml for FTP connector

- src/main/java/org/mule/extension/ftp/internal/command/FtpCopyCommand.java
- src/main/java/org/mule/extension/ftp/internal/command/FtpDeleteCommand.java
- src/main/java/org/mule/extension/ftp/internal/command/FtpListCommand.java
This reverts commit 93edecde9ad375296dc30fccc13703a724c1a07f.
> Revert "W-11697993: Added null validations to FTPList (#305)"

- src/main/java/org/mule/extension/ftp/internal/command/FtpWriteCommand.java
- src/test/munit/configurations.xml
- src/test/munit/ftp-write-test-case.xml
Fix the issue that adding slash to path when no working directory specified
> W-11633025 Fix the issue that adding slash to path when no working directory specified

- src/main/java/org/mule/extension/ftp/internal/command/FtpWriteCommand.java
- src/test/munit/configurations.xml
- src/test/munit/ftp-write-test-case.xml
Cherry-pick for W-11633025.
Fix the issue that adding slash to path when no working directory specified
> W-11633025-1.8.x: Fix the issue that adding slash to path when no working directory specified

- pom.xml
Chore/W-11633025 release 1.8.1
> Chore/W-11633025 release 1.8.1

- pom.xml
* Update dependency com.mulesoft.munit:munit-extensions-maven-plugin to v1.1.3 (#326)
Co-authored-by: Engineering Services Bot <engineering-services-bot@mulesoft.com>
* Update dependency org.apache.maven.plugins:maven-resources-plugin to v3.3.1 (#342)
Co-authored-by: Engineering Services Bot <engineering-services-bot@mulesoft.com>
* Update dependency org.codehaus.mojo:build-helper-maven-plugin to v3.4.0 (#354)
Co-authored-by: Engineering Services Bot <engineering-services-bot@mulesoft.com>
* Update munit.version to v2.3.16 (#353)
Co-authored-by: Engineering Services Bot <engineering-services-bot@mulesoft.com>
Co-authored-by: Tomás Toloza <tomasezequieltoloza@gmail.com>
* Update dependency commons-io:commons-io to v2.12.0 (#356)
Co-authored-by: Engineering Services Bot …
> W-13512345 | Bump dependencies (#360)

- pom.xml
* Update dependency com.mulesoft.munit:munit-extensions-maven-plugin to v1.1.3 (#326)
Co-authored-by: Engineering Services Bot <engineering-services-bot@mulesoft.com>
* Update dependency org.apache.maven.plugins:maven-resources-plugin to v3.3.1 (#342)
Co-authored-by: Engineering Services Bot <engineering-services-bot@mulesoft.com>
* Update dependency org.codehaus.mojo:build-helper-maven-plugin to v3.4.0 (#354)
Co-authored-by: Engineering Services Bot <engineering-services-bot@mulesoft.com>
* Update munit.version to v2.3.16 (#353)
Co-authored-by: Engineering Services Bot <engineering-services-bot@mulesoft.com>
Co-authored-by: Tomás Toloza <tomasezequieltoloza@gmail.com>
* Update dependency commons-io:commons-io to v2.12.0 (#356)
Co-authored-by: Engineering Services Bot …
> W-13512345 | Bump dependencies (#360) (#365)

- pom.xml
_Hi, thank you for your work. We understand that you want to merge your changes and move on from this issue, but we also want to maintain the safety, readability, and testability of our code. Because of this, we kindly ask that you confirm that you have fulfilled the prerequisites for each category of activity before merging your changes._
**NOTE**: _(applies only for Core-Connectors connectors and modules) The release process ends when you merge the pull request that updates the support branch to the new snapshot, please don't forget to do this._
> W-13865565: remove snapshot
